[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/firebasestorage-proxy/*"
  to = "https://firebasestorage.googleapis.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
